<?php
// $id$

/**
 * @file
 * empty module which is used for custom development.
 *
 * Description of the module.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function ding_serendipity_taxonomy_term_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * implements hook_serendipity_info()
 */
function ding_serendipity_taxonomy_term_serendipity_info() {
  return array(
    'recent' => array(
      'title' => 'Recent content of current term',
      'description' => 'Fetch objects from this year matching term.', 
      'keys' => array('taxonomy_tid', 'recent'), 
    ),
    'related_by_term' => array(
      'title' => 'Content with similar term',
      'description' => 'Fetch nodes or materials with similar term.', 
      'keys' => array('taxonomy_tid', 'related'), 
    ),
    'recommended_objects' => array(
      'title' => 'Objects in taxonomy term recommended field', 
      'description' => 'On each taxonomy term a list of recommended objects may be suggested.', 
      'keys' => array('taxonomy_tid', 'recommended'), 
    ),
    'popular_objects' => array(
      'title' => 'Objects in taxonomy term popular field', 
      'description' => 'On each taxonomy term a list of recommended objects may be suggested.', 
      'keys' => array('taxonomy_tid', 'popular'), 
    ),
  );
}

/**
 * Fetch object id's from term recommended field
 * 
 * @context array
 *  Serendipity context array
 *
 * @return array
 *  Array of results, each result should contain a type and an id key.
 *  - type is the entity Type.
 *  - id the entity id.
 * @todo comments
 */
function ding_serendipity_taxonomy_term_recommended_objects_serendipity_add($context) {
  
  // No term no result @todo recommended among recent
  if (isset($context['recent']) || !isset($context['taxonomy_tid']) || !isset($context['bundle']) || ($context['bundle'] != 'ting_object' )) {
    return array();
  }

  $term = taxonomy_term_load($context['taxonomy_tid']);

  $result = ding_serendipity_taxonomy_term_fetch_ting_objects('field_taxonomy_ting_objects', $term);
  return $result;
}

/**
 * Fetch object id's from any term field. 
 * 
 * @field 
 *  Name of field to retrieve
 * @term
 *  Term to retrive objects from
 * @return array
 *  Array of results, each result should contain a type and an id key.
 *  - type is the entity Type.
 *  - id the entity id.
 * @todo comments
 */
function ding_serendipity_taxonomy_term_fetch_ting_objects($field, $term) {
  $result = array();
  
  // Extract id's from field_taxonomy_ting_objects
  $items = field_get_items('taxonomy_term', $term, $field);
  if (!empty($items)) {
    foreach ($items as $item) {
      if (!empty($item['value'])) {
        $result[] = array('type' => 'ting_object', 'id' => $item['value']);
      }
    }
  }
  return $result;
}

/**
 * Fetch ting_objects or nodes matching $context['taxonomy_term']
 * @todo comments
 */
function ding_serendipity_taxonomy_term_recent_serendipity_add($context) {
  $term_arr = ding_serendipity_taxonomy_get_term($context);

  // Validate context  
  if ($term_arr === FALSE || !isset($context['recent'])) {
    return array();
  }

  $term = $term_arr['term'];
  
  // Select content from this year
  $year = date('Y');

  // Apply term query 
  $facets[] = $term_arr['query'];
  
  $query = implode(' AND ', $facets);



  // Order by date 
  $result = ding_serendipity_do_search($query,
    array(
      'options' => array('sort' => 'acquisitionDate_descending'),
      'limit' => 16,
    )
  );
  
  return $result;
}

/*
*
* Helper function to extract term and often used stuff 
*
*/
function ding_serendipity_taxonomy_get_term($context) {
  if (!isset($context['taxonomy_tid']) ) {
    return FALSE;
  }
  
  $term = taxonomy_term_load($context['taxonomy_tid']);
  
  $term_arr = array();
  if (!empty($term->field_search_string)) {
    $term_arr['query'] = $term->field_search_string[field_language('taxonomy_term', $term, 'field_search_string')][0]['value'];
    $term_arr['has_query'] = TRUE;
    $term_arr['has_query'] = TRUE;
  }
  else {
    $term_arr['query'] = $term->name;
    $term_arr['has_query'] = FALSE;
  }
  $term_arr['term'] = $term;
  
  return $term_arr;
}

/**
 * Fetch ting_objects or nodes matching $context['taxonomy_term']
 * @todo comments
 */
function ding_serendipity_taxonomy_term_related_by_term_serendipity_add($context) {
  module_load_include('client.inc', 'ting');
  global $user;
  
  // No term no result
  $term_arr = ding_serendipity_taxonomy_get_term($context);
  if ($term_arr === FALSE || isset($context['recent']))
    return array();
  
  $term = $term_arr['term'];
  $query = $term_arr['query'];
  
  $results = array(); 
  if ($context['bundle'] == 'ting_object') {
    $results = ding_serendipity_do_search($query);
  }
  else {
    // Fetch nodes matching $tid
    $query = db_select('taxonomy_index', 'i');
    $query->join('taxonomy_term_data', 't', 'i.tid = t.tid');
    $query->fields('i', array('nid'));
    $query->condition('i.tid', $term->tid);
    $query->condition('t.vid', 2);
    $query->join('node', 'n', 'n.nid = i.nid');
    $query->fields('n', array('type'));
    
    if (!empty($context['bundle'])) {
      $query->condition('n.type', $context['bundle']);
    }
    $query->range(0, 20);
    $nids = $query->execute();
    foreach ($nids as $nid) {
      $results[] = array('type' => 'node', 'id' => $nid->nid);
    }
  }
  return $results;
}

/**
 * Fetch object id's from term recommended field
 * 
 * @context array
 *  Serendipity context array
 *
 * @return array
 *  Array of results, each result should contain a type and an id key.
 *  - type is the entity Type.
 *  - id the entity id.
 * @todo comments
 */
function ding_serendipity_taxonomy_term_popular_objects_serendipity_add($context) {
  $term = taxonomy_term_load($context['taxonomy_tid']);
  $result = ding_serendipity_taxonomy_term_fetch_ting_objects('field_popular_ting_objects', $term);
  return $result;
}
